version: "3"
services:
  club_app: &app
    image: ghcr.io/toptuk/pmiclub:${GITHUB_SHA:-latest}
    build: 
      dockerfile: Dockerfile
      context: .
    command: make docker-run-production
    container_name: club_app
    environment:
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://pmi.moscow
      - MEDIA_UPLOAD_URL=https://media.pmi.moscow/upload/
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - VIRTUAL_HOST=pmi.moscow,www.pmi.moscow
      - VIRTUAL_PORT=8814
      - VIRTUAL_PATH=/
    env_file:
      - club/.env
    restart: always
    volumes:
      - ./frontend/static:/tmp/static
      #- ./frontend:/app/frontend/ # Vyshka club
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "127.0.0.1:8814:8814"
    networks:
      - front
      - club
    logging:
      driver: "json-file"
      options:
        max-size: "100M"

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []
    networks:
      - club
    logging:
      driver: "json-file"
      options:
        max-size: "100M"

  bot:
    <<: *app
    command: make docker-run-bot
    container_name: club_bot
    environment:
      - APP_HOST=https://pmi.moscow
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_DB=0
      - VIRTUAL_HOST=pmi.moscow
      - VIRTUAL_PATH=/telegram/webhook/
      - VIRTUAL_PORT=8816
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8816:8816"
    networks:
      - club
    logging:
      driver: "json-file"
      options:
        max-size: "100M"

  helpdeskbot:
    <<: *app
    command: make docker-run-helpdeskbot
    container_name: club_help_desk_bot
    environment:
      - APP_HOST=https://pmi.moscow
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_DB=0
      - VIRTUAL_HOST=pmi.moscow
      - VIRTUAL_PATH=/telegram/helpdeskbot/webhook/
      - VIRTUAL_PORT=8817
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8817:8817"
    networks:
      - club
    logging:
      driver: "json-file"
      options:
        max-size: "100M"

  cron:
    <<: *app
    command: make docker-run-cron
    container_name: club_cron
    depends_on:
      - club_app
      - postgres
      - redis
    ports: []
    # networks:
    #   - club
    logging:
      driver: "json-file"
      options:
        max-size: "100M"

  postgres:
    image: postgres:12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: pmiclub
      POSTGRES_PASSWORD: pmiclub
      POSTGRES_DB: pmi_club
    volumes:
      - /root/pmi.moscow.club/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54333:5432"
    networks:
      - club
  
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /root/pmi.moscow.club/backup/pmi/pgdata:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    networks:
      - club

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - club

networks:
  front:
    name: pmi_network
  club:
    name: club_network
