version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-dev
    container_name: club_app
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - .:/app:delegated # enable hot code reload in debug mode
    depends_on:
      - postgres
      - redis
      - queue
      - webpack
    ports:
      - "8000:8000"

  queue:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-queue
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - redis
  
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-bot
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - club_app
      - postgres
      - redis

  postgres:
    image: postgres:11
    container_name: club_postgres
    environment:
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmiclub
      - POSTGRES_DB=pmi_club
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  webpack:
    image: node:14-slim
    command: npm run watch
    restart: always
    volumes:
      - .:/app:delegated
    working_dir: /app/frontend
  
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - /backup/pmi/pgdata:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=pmi_club
      - POSTGRES_USER=pmiclub
      - POSTGRES_PASSWORD=pmi_club
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

networks:
  default:
      name: pmi_network
