name: Build production

on:
  push:
    branches:
      - Deploy

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
      - run: docker build -t ghcr.io/toptuk/pmiclub:latest -t ghcr.io/toptuk/pmiclub:$GITHUB_SHA .
      - run: docker image push ghcr.io/toptuk/pmiclub:$GITHUB_SHA
      - run: docker image push ghcr.io/toptuk/pmiclub:latest